version: '3.7'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=password123
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
